/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CapturePayment201Response,
  CapturePaymentRequest,
  CreatePayment201Response,
  CreatePaymentRequest,
} from '../models/index';
import {
    CapturePayment201ResponseFromJSON,
    CapturePayment201ResponseToJSON,
    CapturePaymentRequestFromJSON,
    CapturePaymentRequestToJSON,
    CreatePayment201ResponseFromJSON,
    CreatePayment201ResponseToJSON,
    CreatePaymentRequestFromJSON,
    CreatePaymentRequestToJSON,
} from '../models/index';

export interface CapturePaymentOperationRequest {
    paymentId: string;
    capturePaymentRequest: CapturePaymentRequest;
}

export interface CreatePaymentOperationRequest {
    createPaymentRequest: CreatePaymentRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Capture a payment
     */
    async capturePaymentRaw(requestParameters: CapturePaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CapturePayment201Response>> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling capturePayment().'
            );
        }

        if (requestParameters['capturePaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'capturePaymentRequest',
                'Required parameter "capturePaymentRequest" was null or undefined when calling capturePayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/payments/{payment_id}/captures`.replace(`{${"payment_id"}}`, encodeURIComponent(String(requestParameters['paymentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CapturePaymentRequestToJSON(requestParameters['capturePaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CapturePayment201ResponseFromJSON(jsonValue));
    }

    /**
     * Capture a payment
     */
    async capturePayment(requestParameters: CapturePaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CapturePayment201Response> {
        const response = await this.capturePaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a payment
     */
    async createPaymentRaw(requestParameters: CreatePaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePayment201Response>> {
        if (requestParameters['createPaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'createPaymentRequest',
                'Required parameter "createPaymentRequest" was null or undefined when calling createPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/payments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaymentRequestToJSON(requestParameters['createPaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePayment201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a payment
     */
    async createPayment(requestParameters: CreatePaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePayment201Response> {
        const response = await this.createPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
