/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CapturePaymentRequest
 */
export interface CapturePaymentRequest {
    /**
     * 
     * @type {object}
     * @memberof CapturePaymentRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CapturePaymentRequest interface.
 */
export function instanceOfCapturePaymentRequest(value: object): value is CapturePaymentRequest {
    return true;
}

export function CapturePaymentRequestFromJSON(json: any): CapturePaymentRequest {
    return CapturePaymentRequestFromJSONTyped(json, false);
}

export function CapturePaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapturePaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

  export function CapturePaymentRequestToJSON(json: any): CapturePaymentRequest {
      return CapturePaymentRequestToJSONTyped(json, false);
  }

  export function CapturePaymentRequestToJSONTyped(value?: CapturePaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': value['metadata'],
    };
}

