/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePayment201ResponseOrderItemsInner } from './CreatePayment201ResponseOrderItemsInner';
import {
    CreatePayment201ResponseOrderItemsInnerFromJSON,
    CreatePayment201ResponseOrderItemsInnerFromJSONTyped,
    CreatePayment201ResponseOrderItemsInnerToJSON,
    CreatePayment201ResponseOrderItemsInnerToJSONTyped,
} from './CreatePayment201ResponseOrderItemsInner';

/**
 * 
 * @export
 * @interface CreatePayment201ResponseOrder
 */
export interface CreatePayment201ResponseOrder {
    /**
     * 
     * @type {Array<CreatePayment201ResponseOrderItemsInner>}
     * @memberof CreatePayment201ResponseOrder
     */
    items?: Array<CreatePayment201ResponseOrderItemsInner>;
    /**
     * 
     * @type {number}
     * @memberof CreatePayment201ResponseOrder
     */
    tax?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePayment201ResponseOrder
     */
    shipping?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseOrder
     */
    orderRef?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseOrder
     */
    updatedAt?: string | null;
}

/**
 * Check if a given object implements the CreatePayment201ResponseOrder interface.
 */
export function instanceOfCreatePayment201ResponseOrder(value: object): value is CreatePayment201ResponseOrder {
    return true;
}

export function CreatePayment201ResponseOrderFromJSON(json: any): CreatePayment201ResponseOrder {
    return CreatePayment201ResponseOrderFromJSONTyped(json, false);
}

export function CreatePayment201ResponseOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePayment201ResponseOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CreatePayment201ResponseOrderItemsInnerFromJSON)),
        'tax': json['tax'] == null ? undefined : json['tax'],
        'shipping': json['shipping'] == null ? undefined : json['shipping'],
        'orderRef': json['order_ref'] == null ? undefined : json['order_ref'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

  export function CreatePayment201ResponseOrderToJSON(json: any): CreatePayment201ResponseOrder {
      return CreatePayment201ResponseOrderToJSONTyped(json, false);
  }

  export function CreatePayment201ResponseOrderToJSONTyped(value?: CreatePayment201ResponseOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CreatePayment201ResponseOrderItemsInnerToJSON)),
        'tax': value['tax'],
        'shipping': value['shipping'],
        'order_ref': value['orderRef'],
        'updated_at': value['updatedAt'],
    };
}

