/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePayment201ResponseCapturesInnerItemsInner } from './CreatePayment201ResponseCapturesInnerItemsInner';
import {
    CreatePayment201ResponseCapturesInnerItemsInnerFromJSON,
    CreatePayment201ResponseCapturesInnerItemsInnerFromJSONTyped,
    CreatePayment201ResponseCapturesInnerItemsInnerToJSON,
    CreatePayment201ResponseCapturesInnerItemsInnerToJSONTyped,
} from './CreatePayment201ResponseCapturesInnerItemsInner';

/**
 * 
 * @export
 * @interface CreatePayment201ResponseCapturesInner
 */
export interface CreatePayment201ResponseCapturesInner {
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseCapturesInner
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePayment201ResponseCapturesInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreatePayment201ResponseCapturesInner
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePayment201ResponseCapturesInner
     */
    tax?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePayment201ResponseCapturesInner
     */
    shipping?: number;
    /**
     * 
     * @type {Array<CreatePayment201ResponseCapturesInnerItemsInner>}
     * @memberof CreatePayment201ResponseCapturesInner
     */
    items?: Array<CreatePayment201ResponseCapturesInnerItemsInner>;
    /**
     * 
     * @type {object}
     * @memberof CreatePayment201ResponseCapturesInner
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CreatePayment201ResponseCapturesInner interface.
 */
export function instanceOfCreatePayment201ResponseCapturesInner(value: object): value is CreatePayment201ResponseCapturesInner {
    return true;
}

export function CreatePayment201ResponseCapturesInnerFromJSON(json: any): CreatePayment201ResponseCapturesInner {
    return CreatePayment201ResponseCapturesInnerFromJSONTyped(json, false);
}

export function CreatePayment201ResponseCapturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePayment201ResponseCapturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'tax': json['tax'] == null ? undefined : json['tax'],
        'shipping': json['shipping'] == null ? undefined : json['shipping'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CreatePayment201ResponseCapturesInnerItemsInnerFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

  export function CreatePayment201ResponseCapturesInnerToJSON(json: any): CreatePayment201ResponseCapturesInner {
      return CreatePayment201ResponseCapturesInnerToJSONTyped(json, false);
  }

  export function CreatePayment201ResponseCapturesInnerToJSONTyped(value?: CreatePayment201ResponseCapturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'amount': value['amount'],
        'tax': value['tax'],
        'shipping': value['shipping'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CreatePayment201ResponseCapturesInnerItemsInnerToJSON)),
        'metadata': value['metadata'],
    };
}

