/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePayment201ResponseCapturesInnerItemsInner
 */
export interface CreatePayment201ResponseCapturesInnerItemsInner {
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseCapturesInnerItemsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseCapturesInnerItemsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseCapturesInnerItemsInner
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePayment201ResponseCapturesInnerItemsInner
     */
    unitPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePayment201ResponseCapturesInnerItemsInner
     */
    quantity?: number;
}

/**
 * Check if a given object implements the CreatePayment201ResponseCapturesInnerItemsInner interface.
 */
export function instanceOfCreatePayment201ResponseCapturesInnerItemsInner(value: object): value is CreatePayment201ResponseCapturesInnerItemsInner {
    return true;
}

export function CreatePayment201ResponseCapturesInnerItemsInnerFromJSON(json: any): CreatePayment201ResponseCapturesInnerItemsInner {
    return CreatePayment201ResponseCapturesInnerItemsInnerFromJSONTyped(json, false);
}

export function CreatePayment201ResponseCapturesInnerItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePayment201ResponseCapturesInnerItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'unitPrice': json['unit_price'] == null ? undefined : json['unit_price'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

  export function CreatePayment201ResponseCapturesInnerItemsInnerToJSON(json: any): CreatePayment201ResponseCapturesInnerItemsInner {
      return CreatePayment201ResponseCapturesInnerItemsInnerToJSONTyped(json, false);
  }

  export function CreatePayment201ResponseCapturesInnerItemsInnerToJSONTyped(value?: CreatePayment201ResponseCapturesInnerItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'unit_price': value['unitPrice'],
        'quantity': value['quantity'],
    };
}

