/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentRequestBuyerData
 */
export interface CreatePaymentRequestBuyerData {
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRequestBuyerData
     */
    age: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRequestBuyerData
     */
    orderCount: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRequestBuyerData
     */
    ltv: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRequestBuyerData
     */
    lastOrderAmount: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRequestBuyerData
     */
    lastOrderAt: number;
}

/**
 * Check if a given object implements the CreatePaymentRequestBuyerData interface.
 */
export function instanceOfCreatePaymentRequestBuyerData(value: object): value is CreatePaymentRequestBuyerData {
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('orderCount' in value) || value['orderCount'] === undefined) return false;
    if (!('ltv' in value) || value['ltv'] === undefined) return false;
    if (!('lastOrderAmount' in value) || value['lastOrderAmount'] === undefined) return false;
    if (!('lastOrderAt' in value) || value['lastOrderAt'] === undefined) return false;
    return true;
}

export function CreatePaymentRequestBuyerDataFromJSON(json: any): CreatePaymentRequestBuyerData {
    return CreatePaymentRequestBuyerDataFromJSONTyped(json, false);
}

export function CreatePaymentRequestBuyerDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentRequestBuyerData {
    if (json == null) {
        return json;
    }
    return {
        
        'age': json['age'],
        'orderCount': json['order_count'],
        'ltv': json['ltv'],
        'lastOrderAmount': json['last_order_amount'],
        'lastOrderAt': json['last_order_at'],
    };
}

  export function CreatePaymentRequestBuyerDataToJSON(json: any): CreatePaymentRequestBuyerData {
      return CreatePaymentRequestBuyerDataToJSONTyped(json, false);
  }

  export function CreatePaymentRequestBuyerDataToJSONTyped(value?: CreatePaymentRequestBuyerData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'age': value['age'],
        'order_count': value['orderCount'],
        'ltv': value['ltv'],
        'last_order_amount': value['lastOrderAmount'],
        'last_order_at': value['lastOrderAt'],
    };
}

