/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePayment201ResponseShippingAddress
 */
export interface CreatePayment201ResponseShippingAddress {
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseShippingAddress
     */
    line1?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseShippingAddress
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseShippingAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseShippingAddress
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseShippingAddress
     */
    zip?: string;
}

/**
 * Check if a given object implements the CreatePayment201ResponseShippingAddress interface.
 */
export function instanceOfCreatePayment201ResponseShippingAddress(value: object): value is CreatePayment201ResponseShippingAddress {
    return true;
}

export function CreatePayment201ResponseShippingAddressFromJSON(json: any): CreatePayment201ResponseShippingAddress {
    return CreatePayment201ResponseShippingAddressFromJSONTyped(json, false);
}

export function CreatePayment201ResponseShippingAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePayment201ResponseShippingAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'line1': json['line1'] == null ? undefined : json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zip': json['zip'] == null ? undefined : json['zip'],
    };
}

  export function CreatePayment201ResponseShippingAddressToJSON(json: any): CreatePayment201ResponseShippingAddress {
      return CreatePayment201ResponseShippingAddressToJSONTyped(json, false);
  }

  export function CreatePayment201ResponseShippingAddressToJSONTyped(value?: CreatePayment201ResponseShippingAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line1': value['line1'],
        'line2': value['line2'],
        'city': value['city'],
        'state': value['state'],
        'zip': value['zip'],
    };
}

