/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentRequestShippingAddress
 */
export interface CreatePaymentRequestShippingAddress {
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestShippingAddress
     */
    line1?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestShippingAddress
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestShippingAddress
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestShippingAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestShippingAddress
     */
    zip: string;
}

/**
 * Check if a given object implements the CreatePaymentRequestShippingAddress interface.
 */
export function instanceOfCreatePaymentRequestShippingAddress(value: object): value is CreatePaymentRequestShippingAddress {
    if (!('zip' in value) || value['zip'] === undefined) return false;
    return true;
}

export function CreatePaymentRequestShippingAddressFromJSON(json: any): CreatePaymentRequestShippingAddress {
    return CreatePaymentRequestShippingAddressFromJSONTyped(json, false);
}

export function CreatePaymentRequestShippingAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentRequestShippingAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'line1': json['line1'] == null ? undefined : json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'state': json['state'] == null ? undefined : json['state'],
        'city': json['city'] == null ? undefined : json['city'],
        'zip': json['zip'],
    };
}

  export function CreatePaymentRequestShippingAddressToJSON(json: any): CreatePaymentRequestShippingAddress {
      return CreatePaymentRequestShippingAddressToJSONTyped(json, false);
  }

  export function CreatePaymentRequestShippingAddressToJSONTyped(value?: CreatePaymentRequestShippingAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line1': value['line1'],
        'line2': value['line2'],
        'state': value['state'],
        'city': value['city'],
        'zip': value['zip'],
    };
}

