/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentRequestOrderItemsInner
 */
export interface CreatePaymentRequestOrderItemsInner {
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRequestOrderItemsInner
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestOrderItemsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestOrderItemsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestOrderItemsInner
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentRequestOrderItemsInner
     */
    unitPrice: number;
}

/**
 * Check if a given object implements the CreatePaymentRequestOrderItemsInner interface.
 */
export function instanceOfCreatePaymentRequestOrderItemsInner(value: object): value is CreatePaymentRequestOrderItemsInner {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
    return true;
}

export function CreatePaymentRequestOrderItemsInnerFromJSON(json: any): CreatePaymentRequestOrderItemsInner {
    return CreatePaymentRequestOrderItemsInnerFromJSONTyped(json, false);
}

export function CreatePaymentRequestOrderItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentRequestOrderItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'unitPrice': json['unit_price'],
    };
}

  export function CreatePaymentRequestOrderItemsInnerToJSON(json: any): CreatePaymentRequestOrderItemsInner {
      return CreatePaymentRequestOrderItemsInnerToJSONTyped(json, false);
  }

  export function CreatePaymentRequestOrderItemsInnerToJSONTyped(value?: CreatePaymentRequestOrderItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'unit_price': value['unitPrice'],
    };
}

