/* tslint:disable */
/* eslint-disable */
/**
 * Paidy Payment API
 * API for creating payments through Paidy.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePayment201ResponseBuyer
 */
export interface CreatePayment201ResponseBuyer {
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseBuyer
     */
    name1?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseBuyer
     */
    name2?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseBuyer
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePayment201ResponseBuyer
     */
    phone?: string;
}

/**
 * Check if a given object implements the CreatePayment201ResponseBuyer interface.
 */
export function instanceOfCreatePayment201ResponseBuyer(value: object): value is CreatePayment201ResponseBuyer {
    return true;
}

export function CreatePayment201ResponseBuyerFromJSON(json: any): CreatePayment201ResponseBuyer {
    return CreatePayment201ResponseBuyerFromJSONTyped(json, false);
}

export function CreatePayment201ResponseBuyerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePayment201ResponseBuyer {
    if (json == null) {
        return json;
    }
    return {
        
        'name1': json['name1'] == null ? undefined : json['name1'],
        'name2': json['name2'] == null ? undefined : json['name2'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

  export function CreatePayment201ResponseBuyerToJSON(json: any): CreatePayment201ResponseBuyer {
      return CreatePayment201ResponseBuyerToJSONTyped(json, false);
  }

  export function CreatePayment201ResponseBuyerToJSONTyped(value?: CreatePayment201ResponseBuyer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name1': value['name1'],
        'name2': value['name2'],
        'email': value['email'],
        'phone': value['phone'],
    };
}

